### ISSUE TITLE
nodemon crashed error : [nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by leslyarun** [RGRjs/express-webpack-template#1]
Hi @samerbuna  I cloned ur repo. I did npm install and npm install -g webpack nodemon.

But if I run nodemon, it always shows the below error and server is not starting at localhost:3000 :

```
$ nodemon
[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `./node_modules/.bin/babel-node --presets react,es2015 server.js`
'.' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting... 
```

**Comment by alifa20** [comment]
Happened to me on windows!

**Comment by samerbuna** [comment]
I don't have a windows machine to test this, but maybe try to have babel-node globally available and test without the full path.

Also, try: nodemon --exec "babel-node --presets react,es2015" server.js

**Comment by garyfoo** [comment]
I have the same problem too :/

**Comment by anchika** [comment]
I am also facing the same issue. How to resolve it?

**Comment by CavalcanteLeo** [comment]
nobody?

**Comment by garyfoo** [comment]
Just an update. I didn't receive the same problem after switching to a mac. Hope this finding can help someone who is on a windows machine

**Comment by CavalcanteLeo** [comment]
it's es6 import problem I think, even using babel, I'm still getting this error

**Comment by CavalcanteLeo** [comment]
`nodemon --exec "babel-node --presets react,es2015" server.js`

this worked like a charm, thank you @samerbuna

**Comment by AndrewLane** [comment]
I'm on Windows, and I switched from forward slashes to escaped backslashes in package.json and I had success:

```
  "scripts": {
    "start": ".\\node_modules\\.bin\\babel-node --presets react,es2015 server.js"
  },
```

Not sure if there's a fully xplat way of pulling this off (still learning).
